"""Init

Revision ID: 75c30cb289bf
Revises: 
Create Date: 2024-02-17 17:55:09.976704

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75c30cb289bf'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subjects')
    op.drop_table('groups')
    op.drop_table('marks')
    op.drop_table('students')
    op.drop_table('lectors')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lectors',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('students',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('group_id_fn', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['group_id_fn'], ['groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('marks',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('value', sa.INTEGER(), nullable=False),
    sa.Column('date_of', sa.DATETIME(), nullable=False),
    sa.Column('subject_id_fn', sa.INTEGER(), nullable=False),
    sa.Column('student_id_fn', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['student_id_fn'], ['students.id'], ),
    sa.ForeignKeyConstraint(['subject_id_fn'], ['subjects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('groups',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subjects',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('lector_id_fn', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['lector_id_fn'], ['lectors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
